@startuml
hide empty description

state "NOT AUTHENTICATED" as na
state "LOGIN\nREQUESTED" as lr
state "NEW ACCOUNT\nREQUESTED" as nar
state "AUTHENTICATED" as a
state "DOCUMENT\nREQUESTED" as dr
state "NEW DOCUMENT\nREQUESTED" as ndr
state "DOCUMENT\nOPENED" as do
state fork_authentication <<fork>>
state join_authentication <<join>>
state fork_document <<fork>>
state join_document <<join>>

[*] --> na

na --> fork_authentication
fork_authentication --> lr : login
fork_authentication --> nar : sign up
lr --> join_authentication
nar --> join_authentication
join_authentication --> a : documents
join_authentication --> na : error

a --> na : logout

a --> fork_document
fork_document --> dr : open
fork_document --> ndr : create
dr --> join_document
ndr --> join_document
join_document --> do : text\n+ sequence of\ncursor
join_document --> a : error
do --> a : close

do --> do : insert / erase / cursor
note as n
   Additionally, an authenticated user can, in whatever state:
   - Modifiy their profile ('profile' messages).
   - Open or create other documents.
end note
@enduml
