name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Install Boost
        run: sudo apt update && sudo apt install -yq libboost-all-dev
      - name: Build
        run: |
          cmake .
          cmake --build .
      - name: Test
        run: ctest .
