name: PlantUML

on: push

jobs:
  plantuml:
    name: Generate PlantUML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate
      uses: grassedge/generate-plantuml-action@v1.4
      with:
        path: docs/plantuml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
