name: PlantUML

on:
  push:
    branches: master
    paths: 'docs/**'

jobs:
  generate_plantuml:
    name: Generate plantUML
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate
      uses: grassedge/generate-plantuml-action@v1.1
      with:
        path: docs/plantuml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
